server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties/
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/