server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/climber1982/springConfig.git
          username:403783154@qq.com
          password:don't tell you